export const SIGN_IN = 'SIGN_IN';
export const LOAD_SIGN_UP = 'LOAD_SIGN_UP';
export const LOAD_LANDING_PAGE = 'LOAD_LANDING_PAGE';
export const API_LOADING = 'API_LOADING';
export const GET_CREDIT = 'GET_CREDIT';
export const SET_RECEIPTS = 'SET_RECEIPTS';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_IMAGE = 'UPDATE_PROFILE_IMAGE';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const TO_HOME_PAGE = 'TO_HOME_PAGE';

export const SET_PLAID_ACCESS_TOKEN = 'SET_PLAID_ACCESS_TOKEN';
export const UPDATE_BANK_ACCOUNT = 'UPDATE_BANK_ACCOUNT';

export const SET_APTO_VERIFICATION_ID = 'SET_APTO_VERIFICATION_ID';
export const SET_APTO_SECONDARY_VERIFICATION_ID = 'SET_APTO_SECONDARY_VERIFICATION_ID';
export const SET_APTO_PHONE_NUMBER = 'SET_APTO_PHONE_NUMBER';
export const SET_APTO_COUNTRY_CODE = 'SET_APTO_COUNTRY_CODE';
export const SET_APTO_NAME_EMAIL = 'SET_APTO_NAME_EMAIL';
export const SET_APTO_ADDRESS = 'SET_APTO_ADDRESS';
export const SET_APTO_BIRTHDATE = 'SET_APTO_BIRTHDATE';
export const SET_APTO_SSN = 'SET_APTO_SSN';
export const SET_APTO_ISSUE_CARD = 'SET_APTO_ISSUE_CARD';
export const SET_TRUPAIDAPTO_ID = 'SET_TRUPAIDAPTO_ID';
export const SET_PAYMENTSOURCE = 'SET_PAYMENTSOURCE';
